image:
  repository: gcr.io/jenkinsxio/jx-build-controller
  tag: 0.0.17

serviceaccount:
  customName: jenkins-x-controllerbuild

internalPort: 8080

probe:
  readypath: "/readyz"
  livepath: "/healthz"

restartPolicy: Always
command:
- jx-build-controller
args: []
env:
  GIT_AUTHOR_NAME: "jenkins-x-bot"
  GIT_AUTHOR_EMAIL: "jenkins-x@googlegroups.com"
  XDG_CONFIG_HOME: "/home/jenkins"
clusterrole:
  enabled: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
  - apiGroups:
    - tekton.dev
    resources:
    - pipelines
    - pipelineruns
    - tasks
    - taskruns
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
role:
  enabled: true
  rules:
  - apiGroups:
    - jenkins.io
    resources:
    - pipelineactivities
    - sourcerepositories
    verbs:
    - list
    - get
    - watch
    - create
    - update
    - patch
  - apiGroups:
    - jenkins.io
    resources:
    - environments
    - plugins
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - tekton.dev
    resources:
    - pipelines
    - pipelineruns
    - tasks
    - taskruns
    verbs:
    - get
    - list
    - watch