apiVersion: jenkins.io/v1
kind: PipelineActivity
metadata:
  annotations:
    lighthouse.jenkins-x.io/cloneURI: https://github.com/jstrachan/nodey532.git
    lighthouse.jenkins-x.io/job: release
  creationTimestamp: null
  labels:
    build: "1"
    created-by-lighthouse: "true"
    event-GUID: 71c43bfc-084c-11eb-8f8d-f3c406f8a4a5
    lighthouse.jenkins-x.io/baseSHA: a086c129ce37779d435145f2f40e0ee3f9eb59ef
    lighthouse.jenkins-x.io/branch: master
    lighthouse.jenkins-x.io/buildNum: "1602040999457"
    lighthouse.jenkins-x.io/context: release
    lighthouse.jenkins-x.io/id: 725cf3e9-084c-11eb-bffc-562f33b53841
    lighthouse.jenkins-x.io/job: release
    lighthouse.jenkins-x.io/lastCommitSHA: a086c129ce37779d435145f2f40e0ee3f9eb59ef
    lighthouse.jenkins-x.io/refs.org: jstrachan
    lighthouse.jenkins-x.io/refs.repo: nodey532
    lighthouse.jenkins-x.io/type: postsubmit
    podName: release-zm5v8-from-build-pack-9f2m9-pod-xsg5h
    tekton.dev/pipeline: release-zm5v8
  name: jstrachan-nodey532-master-1
  namespace: jx
spec:
  baseSHA: a086c129ce37779d435145f2f40e0ee3f9eb59ef
  batchPipelineActivity: {}
  build: "1"
  context: release
  gitBranch: master
  gitOwner: jstrachan
  gitRepository: nodey532
  gitUrl: https://github.com/jstrachan/nodey532.git
  lastCommitSHA: a086c129ce37779d435145f2f40e0ee3f9eb59ef
  pipeline: jstrachan/nodey532/master
  status: Running
  steps:
  - kind: Stage
    stage:
      name: from build pack
      status: Running
      steps:
      - name: Git Clone
        status: Succeeded
      - name: Git Setup
        status: Succeeded
      - name: Git Merge
        status: Succeeded
      - name: Next Version
        status: Succeeded
      - name: Update Version
        status: Succeeded
      - name: Helm Template
        status: Succeeded
      - name: Tag Version
        status: Running
      - name: Setup Builder Home
        status: Pending
      - name: Jx Variables
        status: Pending
      - name: Build Npmrc
        status: Pending
      - name: Build Npm Install
        status: Pending
      - name: Build Npm Test
        status: Pending
      - name: Build Container Build
        status: Pending
      - name: Promote Changelog
        status: Pending
      - name: Promote Helm Release
        status: Pending
      - name: Promote Jx Promote
        status: Pending
status: {}
