{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-16T12:48:16Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: 52448671+hervelemeur@users.noreply.github.com
      name: Hervé Le Meur
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: 'fix: correct chart icon path'
    sha: 4a2c0ea12aac8286413c4841e9d7691963ca1894
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade go dependencies

      from: https://github.com/jenkins-x/jx3-versions
    sha: c3458e1527d5b09ca6012340179e881abebf8180
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-build-controller
  gitOwner: jenkins-x-plugins
  gitRepository: jx-build-controller
  name: '{{ .Chart.Name }}'
  version: 0.0.32
status: {}
 
{{- end }}
