{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-01T11:33:11Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: ugprade dependencies
    sha: 55cad0a88af645d46b6c9a53af10bbae396d733e
  - author:
      email: 52448671+hervelemeur@users.noreply.github.com
      name: Hervé Le Meur
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: 'fix: correct chart icon path'
    sha: 4a2c0ea12aac8286413c4841e9d7691963ca1894
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix ensure we have git setup
    sha: ac00e0c62e0377133782b93027f49a4d65ae261e
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-build-controller
  gitOwner: jenkins-x-plugins
  gitRepository: jx-build-controller
  name: '{{ .Chart.Name }}'
  version: 0.0.33
status: {}
 
{{- end }}
